### ISSUE TITLE
How to stop reading XML?

### ISSUE THREAD

**Issue by gijsstegehuis** [fruux/sabre-xml#109] opened 2016-10-06 14:31 UTC
I tried closing it using close() on XMLReader itself, but this triggers an exception:
"_Sabre\Xml\ParseException: We hit the end of the document prematurely. This likely means that some parser "eats" too many elements. Do not attempt to continue parsing._"

I want to stop reading the file once i found the element.

**Comment by staabm** [comment] 2016-10-06 15:10
Could you post a code snippet which reproduces the problem?

**Comment by evert** [comment] 2016-10-07 00:09
Interesting use-case. I had not thought of this at all. There's no correct way to do this at the moment. The easiest would be to just throw an exception and catch it somewhere else.

**Comment by Obermeijer** [comment] 2016-10-07 06:11
We just figured that, though it's not the cleanest solution 😄 

It's quite an interesting use-case when you don't want to reach the end of the document, especially when dealing with rather large XML files.

**Comment by gijsstegehuis** [comment] 2016-10-07 07:32
Check https://github.com/fruux/sabre-xml/pull/110 for a possible solutions to this.

**Comment by evert** [comment] 2016-11-24 01:35
I'm closing this ticket because it's been a while since the last comment.

If this is indeed still an issue, feel free to comment here so we can continue discussing.

**Closed by evert** 2016-11-24 01:35 UTC
Labels: question
