### ISSUE TITLE
Service: missing encoding

### ISSUE THREAD

**Issue by staabm** [fruux/sabre-xml#92] opened 2016-03-14 08:40 UTC
We produce XML for consumption in glassfish and the XMLs cannot be consumed because of missing encoding declarations.

Hacking `Service::write` with `$w->startDocument('1.0', 'UTF-8')` did the trick for us.
How should the lib consumer tell sabre-xml which encoding the generated XMLs use?

https://github.com/fruux/sabre-xml/blob/master/lib/Service.php#L186

**Comment by evert** [comment] 2016-03-14 16:55
Well, the default for XML is utf-8 as far as I know. So I feel obligated to ask: is this a known glassfish bug?

**Comment by staabm** [comment] 2016-03-17 13:37
ok, just had another talk with my colleague which reported the issue.

the actual issue is, that `$w->startDocument()` renders `<?xml version="1.0"?>` but with `$w->startDocument('1.0', 'UTF-8')` it renders `<?xml version="1.0" encoding="UTF-8"?>` and the `encoding` attribute is required by glassfish

**Comment by evert** [comment] 2016-03-17 21:22
Hey,

So, I understand the issue. I guess what I'm saying is: this should be treated as a glassfish bug, because specifying `encoding` is not required for XML, and glassfish should assume it's UTF-8.

So I am curious if this is a known Glassfish bug. Is it reported somewhere? Is it maybe fixed in a later version?

**Comment by evert** [comment] 2016-03-17 21:23
If it turns out this is not fixable on Glassfish's end, we can definitely come up with a workaround. But I feel that it's important to first address the bug where it actually lives ;) And right now that seems to be glassfish.

**Comment by staabm** [comment] 2016-03-18 06:22
Agree. Where did you find that its not fixable in glassfish?

Does your last comment mean the workaround will land in sabre-xml?

**Comment by staabm** [comment] 2016-03-18 06:25
I misread the comment. I will check the glassfish bugtracker

**Comment by evert** [comment] 2016-10-09 22:16
I'm closing this ticket because it's been a while since the last comment.

If this is indeed still an issue, feel free to comment here so we can continue discussing.

**Closed by evert** 2016-10-09 22:16 UTC

**Comment by davidmpaz** [comment] 2017-03-15 09:02
Hi,
first of all, a big thanks to you @evert for sharing your work and taking time to support us. It is really demanding.

Regarding this issue I would like, if possible, to continue the discussion. I took a read to this thread and tried to check whether client problems arise, wanted to understand also where the problem lies. I dont know if I missed something already so I will describe here. Sorry if post goes long.

I have tested my code on Ubuntu 16.04 with php7.0 and php7.1. I am using phpstorm IDE with editors configured to read UTF-8. I have debug the code and the output of `\Sabre\Xml\Service::write` already comes wrong when no encoding is specified, when I add the encoding everything is nice and dandy.

I dont think I could use an older version of the library since the method call (`startDocument`) is without encoding since its addition to mainstream. Notice also I am not using third party libraries (yet) to consume the output ( no Glassfish ;) ), just php scripts writing xml to file system.

Having this in  mind,  I can confirm that by adding encoding to `startDocument` in here: https://github.com/fruux/sabre-xml/blob/master/lib/Service.php#L186 can be a fix.

In ultimate case I think could be a nice backward compatibility to allow users to specify encoding to the `Service` class. [XMLWriter::startDocument](http://php.net/manual/de/function.xmlwriter-start-document.php) signature explicitly says if no encoding is given, null will be used and under my current situation seems not to default to UTF-8.

Thanks again for your time.
All the best,
David

PD: I could make a pull request to ease things to you if you want.

**Comment by evert** [comment] 2017-03-15 14:21
Hi @davidmpaz ,

I don't want to make this the default, but there's nothing stopping you from subclassing `Service` and overriding the `write` function. I think that's the right way to go for cases like this.

I've also ran into cases where a parser wanted an XML body to end with a newline, and cases where whitespace was not allowed. Both are broken XML parsers, either _can_ be generated with sabre/xml, but you need to take a small extra step and patch in the behavior that you need. I think this is a pretty acceptable workaround for cases such as these.

`Service` is absolutely meant to be sub-classed with new behavior, and we promise to keep that API intact.

**Comment by evert** [comment] 2017-03-15 14:27
It also seems like no effort has been made to report this problem where it should be reported, _in glassfish_. This should really be your first step. That's where the bug is, not here.

**Comment by davidmpaz** [comment] 2017-03-15 14:38
Hi @evert ,

It makes sense. I will go over sub-classing then.

Thanks for pointing in the right direction.
Cheers
