### ISSUE TITLE
mixed text/element in node discards text

### ISSUE THREAD

**Issue by admonkey** [fruux/sabre-xml#107] opened 2016-09-12 19:56 UTC
If my document has mixed text/elements in a node, for example:

```
<root>
   <node>
      some text
      <sub>
          deep text
      </sub>
   </node>
</root>
```

then how can I parse `some text`?

It seems to be simply ignored/discarded when parsed.

Thanks!

**Comment by evert** [comment] 2016-09-13 02:42
Hi @admonkey,

This is by design. The goal of the default deserializer is to easily parse the most common-case. Adding support for mixing text and elements would make parsing unnecessarily complicated.

However, there are specific areas where this makes sense. One example is XHTML embedded into Atom files.

So the question here is, what do you want to do with the data? If your actual use-cases is indeed XHTML inside Atom, you likely want access to the entire sub-document. In that case you'll probably want:

    $service->elementMap('node', 'Sabre\Xml\Elements\XmlFragment');

If there's another more specific parsing strategy you want, you just have to define your own deserializer:

    $service->elementMap('node', function(Sabre\Xml\Reader $reader) {

        // do stuff here and then return.
    });

**Comment by evert** [comment] 2016-09-13 02:42
Closing this issue, but feel free to follow up and ask more questions.

**Closed by evert** 2016-09-13 02:42 UTC
Labels: question
